In [320]:
import pandas as pd

In [321]:
df_fiis = pd.read_csv('database/fiis.csv')
df_fiis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           134 non-null    object
 1   Setor                    134 non-null    object
 2   Preço Atual              127 non-null    object
 3   Liquidez Diária          127 non-null    float64
 4   Dividendo                134 non-null    object
 5   DividendYield            128 non-null    object
 6   DY (3M)Acumulado         128 non-null    object
 7   DY (6M)Acumulado         128 non-null    object
 8   DY (12M)Acumulado        128 non-null    object
 9   DY (3M)Média             128 non-null    object
 10  DY (6M)Média             128 non-null    object
 11  DY (12M)Média            128 non-null    object
 12  DY Ano                   117 non-null    object
 13  Variação Preço           128 non-null    object
 14  Rentab.Período           128 non-null    object
 15  Rentab.Acumulada         128 non-null    object
 16  PatrimônioLíq.           134 non-null    object
 17  VPA                      134 non-null    object
 18  P/VPA                    127 non-null    object
 19  DYPatrimonial            96 non-null     object
 20  VariaçãoPatrimonial      96 non-null     object
 21  Rentab. Patr.no Período  96 non-null     object
 22  Rentab. Patr.Acumulada   96 non-null     object
 23  VacânciaFísica           60 non-null     object
 24  VacânciaFinanceira       16 non-null     object
 25  QuantidadeAtivos         134 non-null    int64
dtypes: float64(1), int64(1), object(24)
memory usage: 27.3+ KB

In [322]:
df_fiis['Preço Atual'] = df_fiis['Preço Atual'].str.replace('R$ ','', regex=False)
df_fiis['Preço Atual'] = df_fiis['Preço Atual'].str.replace(',','.', regex=False)
df_fiis['Dividendo'] = df_fiis['Dividendo'].str.replace('R$ ','', regex=False)
df_fiis['Dividendo'] = df_fiis['Dividendo'].str.replace(',','.', regex=False)
df_fiis['DividendYield'] = df_fiis['DividendYield'].str.replace('%','', regex=False)
df_fiis['DividendYield'] = df_fiis['DividendYield'].str.replace(',','.', regex=False)
df_fiis['DY (3M)Acumulado'] = df_fiis['DY (3M)Acumulado'].str.replace('%','', regex=False)
df_fiis['DY (3M)Acumulado'] = df_fiis['DY (3M)Acumulado'].str.replace(',','.', regex=False)
df_fiis['DY (6M)Acumulado'] = df_fiis['DY (6M)Acumulado'].str.replace('%','', regex=False)
df_fiis['DY (6M)Acumulado'] = df_fiis['DY (6M)Acumulado'].str.replace(',','.', regex=False)
df_fiis['DY (12M)Acumulado'] = df_fiis['DY (12M)Acumulado'].str.replace('%','', regex=False)
df_fiis['DY (12M)Acumulado'] = df_fiis['DY (12M)Acumulado'].str.replace(',','.', regex=False)

df_fiis['DY (3M)Média'] = df_fiis['DY (3M)Média'].str.replace('%','', regex=False)
df_fiis['DY (3M)Média'] = df_fiis['DY (3M)Média'].str.replace(',','.', regex=False)

df_fiis['DY (6M)Média'] = df_fiis['DY (6M)Média'].str.replace('%','', regex=False)
df_fiis['DY (6M)Média'] = df_fiis['DY (6M)Média'].str.replace(',','.', regex=False)

df_fiis['DY (12M)Média'] = df_fiis['DY (12M)Média'].str.replace('%','', regex=False)
df_fiis['DY (12M)Média'] = df_fiis['DY (12M)Média'].str.replace(',','.', regex=False)

df_fiis['DY Ano'] = df_fiis['DY Ano'].str.replace('%','', regex=False)
df_fiis['DY Ano'] = df_fiis['DY Ano'].str.replace(',','.', regex=False)

df_fiis['Variação Preço'] = df_fiis['Variação Preço'].str.replace('%','', regex=False)
df_fiis['Variação Preço'] = df_fiis['Variação Preço'].str.replace(',','.', regex=False)

df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace('%','', regex=False)
df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace(',','.', regex=False)

df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace('%','', regex=False)
df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace(',','.', regex=False)

df_fiis['Rentab.Acumulada'] = df_fiis['Rentab.Acumulada'].str.replace('%','', regex=False)
df_fiis['Rentab.Acumulada'] = df_fiis['Rentab.Acumulada'].str.replace(',','.', regex=False)

df_fiis['PatrimônioLíq.'] = df_fiis['PatrimônioLíq.'].str.replace('R$ ','', regex=False)

df_fiis['VPA'] = df_fiis['VPA'].str.replace(',','.', regex=False)
df_fiis['P/VPA'] = df_fiis['P/VPA'].str.replace(',','.', regex=False)

df_fiis['DYPatrimonial'] = df_fiis['DYPatrimonial'].str.replace('%','', regex=False)
df_fiis['DYPatrimonial'] = df_fiis['DYPatrimonial'].str.replace(',','.', regex=False)

df_fiis['VariaçãoPatrimonial'] = df_fiis['VariaçãoPatrimonial'].str.replace('%','', regex=False)
df_fiis['VariaçãoPatrimonial'] = df_fiis['VariaçãoPatrimonial'].str.replace(',','.', regex=False)

df_fiis['Rentab. Patr.no Período'] = df_fiis['Rentab. Patr.no Período'].str.replace('%','', regex=False)
df_fiis['Rentab. Patr.no Período'] = df_fiis['Rentab. Patr.no Período'].str.replace(',','.', regex=False)

df_fiis['Rentab. Patr.Acumulada'] = df_fiis['Rentab. Patr.Acumulada'].str.replace('%','', regex=False)
df_fiis['Rentab. Patr.Acumulada'] = df_fiis['Rentab. Patr.Acumulada'].str.replace(',','.', regex=False)

df_fiis['VacânciaFísica'] = df_fiis['VacânciaFísica'].str.replace('%','', regex=False)
df_fiis['VacânciaFísica'] = df_fiis['VacânciaFísica'].str.replace(',','.', regex=False)

df_fiis['VacânciaFinanceira'] = df_fiis['VacânciaFinanceira'].str.replace('%','', regex=False)
df_fiis['VacânciaFinanceira'] = df_fiis['VacânciaFinanceira'].str.replace(',','.', regex=False)

df_fiis['VPA'] = df_fiis['VPA'].str.replace('R$ ','', regex=False)

In [323]:
index = 0

for values in df_fiis['Preço Atual'].iteritems():
    
    string_ = str(values[1])
    
    if(len(string_) < 8):
        df_fiis.at[index, 'Preço Atual'] = float(string_)
        index = index + 1
        
    if(len(string_) == 8):
        df_fiis.at[index, 'Preço Atual'] = float(string_[0] + string_[2:] )
        index = index + 1
        
    if(len(string_) == 9):
        df_fiis.at[index, 'Preço Atual'] = float(string_[0:2] + string_[3:] )
        index = index + 1

In [324]:
df_fiis

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
0,FIVN11,Shoppings,2.4,9234.0,0.00,0.00,0.00,0.00,0.00,0.00,...,"65.531.708,68",6.96,0.34,NaN,NaN,NaN,NaN,56.00,NaN,1
1,BZLI11,Títulos e Val. Mob.,14.7,44041.0,0.00,0.00,0.00,0.00,0.00,0.00,...,"439.856.409,07",10.80,1.36,NaN,NaN,NaN,NaN,NaN,NaN,0
2,XTED11,Lajes Corporativas,6.07,7389.0,0.00,0.00,0.00,0.00,0.00,0.00,...,"27.172.278,20",13.83,0.44,NaN,NaN,NaN,NaN,0.00,100.00,1
3,ALMI11,Lajes Corporativas,840.0,20.0,0.00,0.00,0.00,0.00,0.00,0.00,...,"249.878.508,15",2.247.57,0.37,NaN,NaN,NaN,NaN,64.05,NaN,1
4,PABY11,Híbrido,16.0,362.0,0.00,0.00,0.00,0.00,0.00,0.00,...,"-10.622.559,80",-14.01,-1.14,NaN,NaN,NaN,NaN,NaN,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,HGPO11,Lajes Corporativas,259.0,917.0,1.50,0.59,1.63,3.19,6.56,0.54,...,"470.128.332,27",268.18,0.97,0.56,-0.03,0.53,3.68,4.99,2.72,2
130,HGLG11,Logística,169.14,33466.0,1.10,0.65,3.33,5.33,9.69,1.11,...,"3.430.789.490,17",146.26,1.16,0.75,-0.22,0.53,5.35,6.90,6.50,17
131,HGCR11,Títulos e Val. Mob.,104.0,43942.0,1.20,1.16,3.39,6.42,11.92,1.13,...,"1.491.890.744,95",101.72,1.02,1.18,-0.78,0.39,8.04,NaN,NaN,0
132,HGRE11,Lajes Corporativas,139.67,12577.0,0.78,0.63,1.83,3.53,8.24,0.61,...,"1.914.484.396,71",162.00,0.86,0.48,-0.16,0.32,0.90,27.13,29.17,21
133,MXRF11,Híbrido,10.08,520493.0,0.12,1.22,3.37,6.54,11.72,1.12,...,"2.302.693.543,19",10.19,0.99,0.98,-0.02,0.96,2.22,NaN,NaN,0

In [325]:
index = 0

for values in df_fiis['PatrimônioLíq.'].iteritems():
    
    string_ = str(values[1])
    
    if(len(string_) == 12):
        df_fiis.at[index, 'PatrimônioLíq.'] = float((string_[0:1] + string_[2:5] + string_[6:]).replace(',','.'))
    
    if(len(string_) == 13):
        df_fiis.at[index, 'PatrimônioLíq.'] = float((string_[0:2] + string_[3:6] + string_[7:]).replace(',','.'))
        
    
    if(len(string_) == 14):
        string_to_float = string_[0:3] + string_[4:7] + string_[8:]
        string_to_float = string_to_float.replace(',','.')
        df_fiis.at[index, 'PatrimônioLíq.'] = float(string_to_float)
        #print(float(string_to_float))
    
    if(len(string_) == 16):
        string_to_float = string_[0:1] + string_[2:5] + string_[6:9] + string_[10:]
        string_to_float = string_to_float.replace(',','.')
        df_fiis.at[index, 'PatrimônioLíq.'] = float(string_to_float)
        #print(float(string_to_float))
    
    index = index + 1

In [326]:
df_fiis['PatrimônioLíq.']

0        65531708.68
1       439856409.07
2         27172278.2
3       249878508.15
4        -10622559.8
           ...
129     470128332.27
130    3430789490.17
131    1491890744.95
132    1914484396.71
133    2302693543.19
Name: PatrimônioLíq., Length: 134, dtype: object

In [327]:
index = 0
for values in df_fiis['VPA'].iteritems():
    string_ = str(values[1])
    
    if(len(string_) == 8):
        df_fiis.at[index, 'VPA'] = float((string_[0:1] + string_[2:]))
        
    index = index + 1

In [328]:
df_fiis.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [329]:
df_fiis["Códigodo fundo"] = df_fiis["Códigodo fundo"].astype('category')
df_fiis["Setor"] = df_fiis["Setor"].astype('category')

cols_float = ['Preço Atual','Dividendo', 'DividendYield', 
              'DY (3M)Acumulado', 'DY (6M)Acumulado' , 
              'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média',
              'DY (12M)Média','DY Ano', 'Variação Preço',
              'Rentab.Período', 'Rentab.Acumulada','PatrimônioLíq.', 
              'VPA', 'P/VPA', 'DYPatrimonial',
              'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
              'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
              'QuantidadeAtivos'
             ]

for col in cols_float:
     df_fiis[f'{col}'] = df_fiis[f'{col}'].astype('float')
df_fiis.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 26 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Códigodo fundo           134 non-null    category
 1   Setor                    134 non-null    category
 2   Preço Atual              127 non-null    float64
 3   Liquidez Diária          127 non-null    float64
 4   Dividendo                134 non-null    float64
 5   DividendYield            128 non-null    float64
 6   DY (3M)Acumulado         128 non-null    float64
 7   DY (6M)Acumulado         128 non-null    float64
 8   DY (12M)Acumulado        128 non-null    float64
 9   DY (3M)Média             128 non-null    float64
 10  DY (6M)Média             128 non-null    float64
 11  DY (12M)Média            128 non-null    float64
 12  DY Ano                   117 non-null    float64
 13  Variação Preço           128 non-null    float64
 14  Rentab.Período           128 non-null    float64
 15  Rentab.Acumulada         128 non-null    float64
 16  PatrimônioLíq.           134 non-null    float64
 17  VPA                      134 non-null    float64
 18  P/VPA                    127 non-null    float64
 19  DYPatrimonial            96 non-null     float64
 20  VariaçãoPatrimonial      96 non-null     float64
 21  Rentab. Patr.no Período  96 non-null     float64
 22  Rentab. Patr.Acumulada   96 non-null     float64
 23  VacânciaFísica           60 non-null     float64
 24  VacânciaFinanceira       16 non-null     float64
 25  QuantidadeAtivos         134 non-null    float64
dtypes: category(2), float64(24)
memory usage: 31.1 KB

In [330]:
df_fiis

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,Dividendo,DividendYield,DY (3M)Acumulado,DY (6M)Acumulado,DY (12M)Acumulado,DY (3M)Média,...,PatrimônioLíq.,VPA,P/VPA,DYPatrimonial,VariaçãoPatrimonial,Rentab. Patr.no Período,Rentab. Patr.Acumulada,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
0,FIVN11,Shoppings,2.40,9234.0,0.00,0.00,0.00,0.00,0.00,0.00,...,6.553171e+07,6.96,0.34,NaN,NaN,NaN,NaN,56.00,NaN,1.0
1,BZLI11,Títulos e Val. Mob.,14.70,44041.0,0.00,0.00,0.00,0.00,0.00,0.00,...,4.398564e+08,10.80,1.36,NaN,NaN,NaN,NaN,NaN,NaN,0.0
2,XTED11,Lajes Corporativas,6.07,7389.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.717228e+07,13.83,0.44,NaN,NaN,NaN,NaN,0.00,100.00,1.0
3,ALMI11,Lajes Corporativas,840.00,20.0,0.00,0.00,0.00,0.00,0.00,0.00,...,2.498785e+08,2247.57,0.37,NaN,NaN,NaN,NaN,64.05,NaN,1.0
4,PABY11,Híbrido,16.00,362.0,0.00,0.00,0.00,0.00,0.00,0.00,...,-1.062256e+07,-14.01,-1.14,NaN,NaN,NaN,NaN,NaN,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129,HGPO11,Lajes Corporativas,259.00,917.0,1.50,0.59,1.63,3.19,6.56,0.54,...,4.701283e+08,268.18,0.97,0.56,-0.03,0.53,3.68,4.99,2.72,2.0
130,HGLG11,Logística,169.14,33466.0,1.10,0.65,3.33,5.33,9.69,1.11,...,3.430789e+09,146.26,1.16,0.75,-0.22,0.53,5.35,6.90,6.50,17.0
131,HGCR11,Títulos e Val. Mob.,104.00,43942.0,1.20,1.16,3.39,6.42,11.92,1.13,...,1.491891e+09,101.72,1.02,1.18,-0.78,0.39,8.04,NaN,NaN,0.0
132,HGRE11,Lajes Corporativas,139.67,12577.0,0.78,0.63,1.83,3.53,8.24,0.61,...,1.914484e+09,162.00,0.86,0.48,-0.16,0.32,0.90,27.13,29.17,21.0
133,MXRF11,Híbrido,10.08,520493.0,0.12,1.22,3.37,6.54,11.72,1.12,...,2.302694e+09,10.19,0.99,0.98,-0.02,0.96,2.22,NaN,NaN,0.0