In [151]:
import pandas as pd

In [152]:
df_fiis = pd.read_csv('database/fiis.csv')
df_fiis.info()

<class 'pandas.core.frame.DataFrame'>
Index: 0 entries
Data columns (total 32 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Unnamed: 0               0 non-null      object
 1   Unnamed: 1               0 non-null      object
 2   Unnamed: 2               0 non-null      object
 3   Unnamed: 3               0 non-null      object
 4   Unnamed: 4               0 non-null      object
 5   Unnamed: 5               0 non-null      object
 6   Códigodo fundo           0 non-null      object
 7   Setor                    0 non-null      object
 8   Preço Atual              0 non-null      object
 9   Liquidez Diária          0 non-null      object
 10  Dividendo                0 non-null      object
 11  DividendYield            0 non-null      object
 12  DY (3M)Acumulado         0 non-null      object
 13  DY (6M)Acumulado         0 non-null      object
 14  DY (12M)Acumulado        0 non-null      object
 15  DY (3M)Média             0 non-null      object
 16  DY (6M)Média             0 non-null      object
 17  DY (12M)Média            0 non-null      object
 18  DY Ano                   0 non-null      object
 19  Variação Preço           0 non-null      object
 20  Rentab.Período           0 non-null      object
 21  Rentab.Acumulada         0 non-null      object
 22  PatrimônioLíq.           0 non-null      object
 23  VPA                      0 non-null      object
 24  P/VPA                    0 non-null      object
 25  DYPatrimonial            0 non-null      object
 26  VariaçãoPatrimonial      0 non-null      object
 27  Rentab. Patr.no Período  0 non-null      object
 28  Rentab. Patr.Acumulada   0 non-null      object
 29  VacânciaFísica           0 non-null      object
 30  VacânciaFinanceira       0 non-null      object
 31  Quantidade               0 non-null      object
dtypes: object(32)
memory usage: 0.0+ bytes

In [153]:
df_fiis['Preço Atual'] = df_fiis['Preço Atual'].str.replace('R$ ','', regex=False)
df_fiis['Preço Atual'] = df_fiis['Preço Atual'].str.replace(',','.', regex=False)
df_fiis['Dividendo'] = df_fiis['Dividendo'].str.replace('R$ ','', regex=False)
df_fiis['Dividendo'] = df_fiis['Dividendo'].str.replace(',','.', regex=False)
df_fiis['DividendYield'] = df_fiis['DividendYield'].str.replace('%','', regex=False)
df_fiis['DividendYield'] = df_fiis['DividendYield'].str.replace(',','.', regex=False)
df_fiis['DY (3M)Acumulado'] = df_fiis['DY (3M)Acumulado'].str.replace('%','', regex=False)
df_fiis['DY (3M)Acumulado'] = df_fiis['DY (3M)Acumulado'].str.replace(',','.', regex=False)
df_fiis['DY (6M)Acumulado'] = df_fiis['DY (6M)Acumulado'].str.replace('%','', regex=False)
df_fiis['DY (6M)Acumulado'] = df_fiis['DY (6M)Acumulado'].str.replace(',','.', regex=False)
df_fiis['DY (12M)Acumulado'] = df_fiis['DY (12M)Acumulado'].str.replace('%','', regex=False)
df_fiis['DY (12M)Acumulado'] = df_fiis['DY (12M)Acumulado'].str.replace(',','.', regex=False)

df_fiis['DY (3M)Média'] = df_fiis['DY (3M)Média'].str.replace('%','', regex=False)
df_fiis['DY (3M)Média'] = df_fiis['DY (3M)Média'].str.replace(',','.', regex=False)

df_fiis['DY (6M)Média'] = df_fiis['DY (6M)Média'].str.replace('%','', regex=False)
df_fiis['DY (6M)Média'] = df_fiis['DY (6M)Média'].str.replace(',','.', regex=False)

df_fiis['DY (12M)Média'] = df_fiis['DY (12M)Média'].str.replace('%','', regex=False)
df_fiis['DY (12M)Média'] = df_fiis['DY (12M)Média'].str.replace(',','.', regex=False)

df_fiis['DY Ano'] = df_fiis['DY Ano'].str.replace('%','', regex=False)
df_fiis['DY Ano'] = df_fiis['DY Ano'].str.replace(',','.', regex=False)

df_fiis['Variação Preço'] = df_fiis['Variação Preço'].str.replace('%','', regex=False)
df_fiis['Variação Preço'] = df_fiis['Variação Preço'].str.replace(',','.', regex=False)

df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace('%','', regex=False)
df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace(',','.', regex=False)

df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace('%','', regex=False)
df_fiis['Rentab.Período'] = df_fiis['Rentab.Período'].str.replace(',','.', regex=False)

df_fiis['Rentab.Acumulada'] = df_fiis['Rentab.Acumulada'].str.replace('%','', regex=False)
df_fiis['Rentab.Acumulada'] = df_fiis['Rentab.Acumulada'].str.replace(',','.', regex=False)

df_fiis['PatrimônioLíq.'] = df_fiis['PatrimônioLíq.'].str.replace('R$ ','', regex=False)

df_fiis['VPA'] = df_fiis['VPA'].str.replace(',','.', regex=False)
df_fiis['P/VPA'] = df_fiis['P/VPA'].str.replace(',','.', regex=False)

df_fiis['DYPatrimonial'] = df_fiis['DYPatrimonial'].str.replace('%','', regex=False)
df_fiis['DYPatrimonial'] = df_fiis['DYPatrimonial'].str.replace(',','.', regex=False)

df_fiis['VariaçãoPatrimonial'] = df_fiis['VariaçãoPatrimonial'].str.replace('%','', regex=False)
df_fiis['VariaçãoPatrimonial'] = df_fiis['VariaçãoPatrimonial'].str.replace(',','.', regex=False)

df_fiis['Rentab. Patr.no Período'] = df_fiis['Rentab. Patr.no Período'].str.replace('%','', regex=False)
df_fiis['Rentab. Patr.no Período'] = df_fiis['Rentab. Patr.no Período'].str.replace(',','.', regex=False)

df_fiis['Rentab. Patr.Acumulada'] = df_fiis['Rentab. Patr.Acumulada'].str.replace('%','', regex=False)
df_fiis['Rentab. Patr.Acumulada'] = df_fiis['Rentab. Patr.Acumulada'].str.replace(',','.', regex=False)

df_fiis['VacânciaFísica'] = df_fiis['VacânciaFísica'].str.replace('%','', regex=False)
df_fiis['VacânciaFísica'] = df_fiis['VacânciaFísica'].str.replace(',','.', regex=False)

df_fiis['VacânciaFinanceira'] = df_fiis['VacânciaFinanceira'].str.replace('%','', regex=False)
df_fiis['VacânciaFinanceira'] = df_fiis['VacânciaFinanceira'].str.replace(',','.', regex=False)

df_fiis['VPA'] = df_fiis['VPA'].str.replace('R$ ','', regex=False)

In [154]:
index = 0

for values in df_fiis['Preço Atual'].iteritems():
    
    string_ = str(values[1])
    
    if(len(string_) < 8):
        df_fiis.at[index, 'Preço Atual'] = float(string_)
        index = index + 1
        
    if(len(string_) == 8):
        df_fiis.at[index, 'Preço Atual'] = float(string_[0] + string_[2:] )
        index = index + 1
        
    if(len(string_) == 9):
        df_fiis.at[index, 'Preço Atual'] = float(string_[0:2] + string_[3:] )
        index = index + 1

In [155]:
df_fiis

Empty DataFrame
Columns: [Unnamed: 0, Unnamed: 1, Unnamed: 2, Unnamed: 3, Unnamed: 4, Unnamed: 5, Códigodo fundo, Setor, Preço Atual, Liquidez Diária, Dividendo, DividendYield, DY (3M)Acumulado, DY (6M)Acumulado, DY (12M)Acumulado, DY (3M)Média, DY (6M)Média, DY (12M)Média, DY Ano, Variação Preço, Rentab.Período, Rentab.Acumulada, PatrimônioLíq., VPA, P/VPA, DYPatrimonial, VariaçãoPatrimonial, Rentab. Patr.no Período, Rentab. Patr.Acumulada, VacânciaFísica, VacânciaFinanceira, Quantidade]
Index: []

[0 rows x 32 columns]

In [156]:
df_fiis.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Códigodo fundo', 'Setor', 'Preço Atual',
       'Liquidez Diária', 'Dividendo', 'DividendYield', 'DY (3M)Acumulado',
       'DY (6M)Acumulado', 'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média',
       'DY (12M)Média', 'DY Ano', 'Variação Preço', 'Rentab.Período',
       'Rentab.Acumulada', 'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'Quantidade'],
      dtype='object')

In [157]:
index = 0

for values in df_fiis['PatrimônioLíq.'].iteritems():
    
    string_ = str(values[1])
    
    if(len(string_) == 12):
        df_fiis.at[index, 'PatrimônioLíq.'] = float((string_[0:1] + string_[2:5] + string_[6:]).replace(',','.'))
    
    if(len(string_) == 13):
        df_fiis.at[index, 'PatrimônioLíq.'] = float((string_[0:2] + string_[3:6] + string_[7:]).replace(',','.'))
        
    
    if(len(string_) == 14):
        string_to_float = string_[0:3] + string_[4:7] + string_[8:]
        string_to_float = string_to_float.replace(',','.')
        df_fiis.at[index, 'PatrimônioLíq.'] = float(string_to_float)
        #print(float(string_to_float))
    
    if(len(string_) == 16):
        string_to_float = string_[0:1] + string_[2:5] + string_[6:9] + string_[10:]
        string_to_float = string_to_float.replace(',','.')
        df_fiis.at[index, 'PatrimônioLíq.'] = float(string_to_float)
        #print(float(string_to_float))
    
    index = index + 1

In [158]:
df_fiis['PatrimônioLíq.']

Series([], Name: PatrimônioLíq., dtype: object)

In [159]:
index = 0
for values in df_fiis['VPA'].iteritems():
    string_ = str(values[1])
    
    if(len(string_) == 8):
        df_fiis.at[index, 'VPA'] = float((string_[0:1] + string_[2:]))
        
    index = index + 1

In [160]:
df_fiis.columns

Index(['Unnamed: 0', 'Unnamed: 1', 'Unnamed: 2', 'Unnamed: 3', 'Unnamed: 4',
       'Unnamed: 5', 'Códigodo fundo', 'Setor', 'Preço Atual',
       'Liquidez Diária', 'Dividendo', 'DividendYield', 'DY (3M)Acumulado',
       'DY (6M)Acumulado', 'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média',
       'DY (12M)Média', 'DY Ano', 'Variação Preço', 'Rentab.Período',
       'Rentab.Acumulada', 'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'Quantidade'],
      dtype='object')

In [161]:
df_fiis["Códigodo fundo"] = df_fiis["Códigodo fundo"].astype('category')
df_fiis["Setor"] = df_fiis["Setor"].astype('category')

cols_float = ['Preço Atual','Dividendo', 'DividendYield', 
              'DY (3M)Acumulado', 'DY (6M)Acumulado' , 
              'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média',
              'DY (12M)Média','DY Ano', 'Variação Preço',
              'Rentab.Período', 'Rentab.Acumulada','PatrimônioLíq.', 
              'VPA', 'P/VPA', 'DYPatrimonial',
              'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
              'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
              'QuantidadeAtivos'
             ]

for col in cols_float:
     df_fiis[f'{col}'] = df_fiis[f'{col}'].astype('float')
df_fiis.info()

KeyError: 'QuantidadeAtivos'

In [ ]:
df_fiis.columns

Index(['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
       'Dividendo', 'DividendYield', 'DY (3M)Acumulado', 'DY (6M)Acumulado',
       'DY (12M)Acumulado', 'DY (3M)Média', 'DY (6M)Média', 'DY (12M)Média',
       'DY Ano', 'Variação Preço', 'Rentab.Período', 'Rentab.Acumulada',
       'PatrimônioLíq.', 'VPA', 'P/VPA', 'DYPatrimonial',
       'VariaçãoPatrimonial', 'Rentab. Patr.no Período',
       'Rentab. Patr.Acumulada', 'VacânciaFísica', 'VacânciaFinanceira',
       'QuantidadeAtivos'],
      dtype='object')

In [ ]:
COLS_SELECTED = ['Códigodo fundo', 'Setor', 'Preço Atual', 'Liquidez Diária',
                 'DividendYield', 'DY (12M)Acumulado', 'DY Ano',  
                 'PatrimônioLíq.', 'VPA', 'P/VPA', 'VariaçãoPatrimonial',
                 'VacânciaFísica', 'VacânciaFinanceira',
                 'QuantidadeAtivos'
                ]

In [ ]:
def filter_rows_by_values(df, col, values):
    return df[~df[col].isin(values) == False]

codefiis = ['KNCR11', 
            'HSML11', 
            'MXRF11',
            'VINO11',
            'HGLG11',
            'HGRU11',
            'XPLG11',
            'BTLG11',
           ]

df_fiis_selected = filter_rows_by_values(df_fiis[COLS_SELECTED], "Códigodo fundo", codefiis)

In [ ]:
# 2022-09-03 fiis - allocated 
df_fiis_selected

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,DividendYield,DY (12M)Acumulado,DY Ano,PatrimônioLíq.,VPA,P/VPA,VariaçãoPatrimonial,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
53,HGRU11,Híbrido,124.00,32355.0,0.69,8.38,5.17,2.176483e+09,118.25,1.05,-0.01,0.0,0.0,17.0
90,KNCR11,Títulos e Val. Mob.,102.16,79636.0,1.12,9.92,6.79,4.447594e+09,101.40,1.01,0.31,NaN,NaN,0.0
94,HSML11,Shoppings,86.86,35705.0,0.84,8.75,5.43,1.560544e+09,98.89,0.88,0.00,4.5,NaN,6.0
107,VINO11,Lajes Corporativas,48.88,26889.0,0.77,9.80,4.99,8.909712e+08,53.79,0.91,-0.40,4.2,NaN,9.0
130,HGLG11,Logística,169.14,33466.0,0.65,9.69,5.98,3.430789e+09,146.26,1.16,-0.22,6.9,6.5,17.0
133,MXRF11,Híbrido,10.08,520493.0,1.22,11.72,7.53,2.302694e+09,10.19,0.99,-0.02,NaN,NaN,0.0

In [ ]:
#codefiis = ['HTMX11', 'VISC11'
#           ]

codeffis = ['BRCO11']

df_fiis_selected = filter_rows_by_values(df_fiis[COLS_SELECTED], "Códigodo fundo", codefiis)
df_fiis_selected

,Códigodo fundo,Setor,Preço Atual,Liquidez Diária,DividendYield,DY (12M)Acumulado,DY Ano,PatrimônioLíq.,VPA,P/VPA,VariaçãoPatrimonial,VacânciaFísica,VacânciaFinanceira,QuantidadeAtivos
53,HGRU11,Híbrido,124.00,32355.0,0.69,8.38,5.17,2.176483e+09,118.25,1.05,-0.01,0.0,0.0,17.0
90,KNCR11,Títulos e Val. Mob.,102.16,79636.0,1.12,9.92,6.79,4.447594e+09,101.40,1.01,0.31,NaN,NaN,0.0
94,HSML11,Shoppings,86.86,35705.0,0.84,8.75,5.43,1.560544e+09,98.89,0.88,0.00,4.5,NaN,6.0
107,VINO11,Lajes Corporativas,48.88,26889.0,0.77,9.80,4.99,8.909712e+08,53.79,0.91,-0.40,4.2,NaN,9.0
130,HGLG11,Logística,169.14,33466.0,0.65,9.69,5.98,3.430789e+09,146.26,1.16,-0.22,6.9,6.5,17.0
133,MXRF11,Híbrido,10.08,520493.0,1.22,11.72,7.53,2.302694e+09,10.19,0.99,-0.02,NaN,NaN,0.0